# Evaluation Notebook for FL Simulations

In [8]:
import os
import pickle
import pandas as pd

from utils import tools

In [17]:
data = 'pvod'
model = 'fnn'
output_dim = 1
freq = '1h'

config = tools.load_config('config.yaml')
results_dir = config['eval']['results_path']
results_dir = os.path.join(results_dir, data)

sim = f'fl_d-{data}_m-{model}_out-{output_dim}_freq-{freq}.pkl'

In [18]:
with open(os.path.join(results_dir, sim), 'rb') as f:
    results = pickle.load(f)

In [19]:
results.keys()

dict_keys(['model', 'history', 'hyperparameters', 'evaluation'])

In [24]:
results['evaluation']

,R^2,RMSE,MAE,Skill,output_dim,freq,key,t_0
Models,,,,,,,,
fnn,0.760354,0.111799,0.060461,0.180722,1,1h,station00.csv,None
fnn,0.912810,0.089683,0.047287,0.421738,1,1h,station01.csv,None
fnn,0.900478,0.080986,0.045536,0.449972,1,1h,station02.csv,None
fnn,0.819798,0.104797,0.062264,0.219924,1,1h,station03.csv,None
fnn,0.855178,0.146205,0.081791,0.401551,1,1h,station04.csv,None
fnn,0.802922,0.122453,0.072382,0.183653,1,1h,station05.csv,None
fnn,0.717979,0.112792,0.064748,-0.025848,1,1h,station06.csv,None
fnn,0.817020,0.105747,0.058395,0.273045,1,1h,station07.csv,None
fnn,0.845412,0.099202,0.055347,0.332567,1,1h,station08.csv,None
fnn,-0.805980,0.190699,0.124634,-1.203813,1,1h,station09.csv,None

In [28]:
results['history']['metrics_aggregated']

       train_loss  train_mae  train_rmse  eval_loss  eval_mae  eval_rmse
round
1        0.003985   0.036954    0.059612   0.010513  0.059968   0.099951
2        0.003110   0.030583    0.052063   0.010207  0.056178   0.097619